name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: docs

      - name: Configure preview URL
        run: |
          PREVIEW_URL="https://arm-university.github.io/pr-preview/pr-${{ github.event.pull_request.number }}"
          echo "url: ${PREVIEW_URL}" > docs/_config_preview.yml
          echo "baseurl: ''" >> docs/_config_preview.yml
        
      - name: Build with Jekyll
        run: |
          cd docs
          bundle install
          bundle exec jekyll build --config _config.yml,_config_preview.yml
        
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          preview-branch: gh-pages
          source-dir: ./docs/_site/
          pages-base-path: ./docs/
